server {
    listen 80;
    root /var/www/html/web;

    location / {
        # Intentamos servir el archivo real, si no, vamos al controlador de Symfony
        try_files $uri /app.php$is_args$args;
    }

    # Configuración para app.php y app_dev.php
    location ~ ^/(app|app_dev)\.php(/|$) {
        fastcgi_pass app:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS off;
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}